### ISSUE TITLE
[Bug Report] vupress-types: themeConfig is not optional in siteData

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-community#15]
I am meeting error with `themeConfig` in `SiteData` [here](https://github.com/vuepress/vuepress-community/blob/master/packages/vuepress-types/types/config.d.ts#L67)

If there isn't any config, vuepress will generate a `{}` for themeConfig here. 

Now the expression like `this.$themeConfig.nav` in the default theme catches error because ts will think themeConfig can be undefined. If effects almost all the vue files in `theme-default` package .

For detail, you can simply add a folder with only a README.md file in it add let vuepress server it.

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/72775168-4d468300-3c48-11ea-8990-f84d12369abb.png)

**Comment by meteorlxy** [comment]
Confirm that there are some problems with `this.$site.themeConfig`.

But `this.$themeConfig` should work.

**Comment by meteorlxy** [comment]
Fixed in vuepress-types@0.8.0

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/72790371-711dbf00-3c70-11ea-9557-0c6078e77724.png)
![image](https://user-images.githubusercontent.com/33315834/72790380-72e78280-3c70-11ea-8c46-b4823d57a9fa.png)

Excuse me, still catching errors in my project which I am tring to rewrite the `theme-default` package with ts.

**Comment by meteorlxy** [comment]
upgrade to the latest version, plz

**Comment by Mister-Hope** [comment]
I did, you can see the screen shot, my vscode see `this.$site` as 

```
Vue.$site: Pick<SiteConfig, "title" | "description" | "base" | "themeConfig" | "locales"> & {
    pages: PageComputed[];
}
```

But still see `themeConfig` as `themeConfig?: ThemeConfig | undefined`

**Comment by Mister-Hope** [comment]
It's your mistake, `Pick` is just pickup some property. You pick from `SiteConfig`, but in it , there is still `themeConfig?: ThemeConfig`
